# Site settings
title: Sanil Pande
description: Personal Website
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Sanil Pande
user_description:
user_title: Computer Vision and Robotics Enthusiast
email: sanil.pande@gmail.com
# twitter_username: lorem_ipsum
github_username:  sanilpande
linkedin_username: sanilpande
instagram_username: sanil.pande
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: UA-134207126-1

exclude: ['package.json', 'src' , 'node_modules']

theme: jekyll-theme-time-machine
